import { env } from "@/env/client"

const simulateAiResponse = async (userRequest: string) => {
  await new Promise((resolve) => setTimeout(resolve, 1500))

  const firstLine = userRequest.split("\n")[0] || "Task"
  const title = firstLine.length > 50 ? `${firstLine.substring(0, 47)}...` : firstLine

  const description = `This is a simulated AI-generated task description for: "${userRequest}".

Key Details:
- Task priority: Medium
- Estimated completion time: 2-3 hours
- Required resources: Documentation, team input

Steps to Complete:
1. Analyze requirements
2. Create initial draft
3. Gather feedback from stakeholders
4. Finalize and implement
5. Review and validate results

Additional Notes:
This task should be completed according to company standards and best practices. Regular updates on progress are recommended.`

  return { title, description }
}

export async function generateTaskDraft(userRequest: string) {
  try {
    try {
      const apiKey = env.NEXT_PUBLIC_GEMINI_API_KEY

      if (!apiKey) {
        throw new Error("Gemini API key not found")
      }

      const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`

      const requestBody = {
        contents: [
          {
            role: "user",
            parts: [
              {
                text: `You are a structured task management AI. Your job is to generate a concise task title and a brief task description based on a user's request.

STRICTLY follow this output format:

{
  "title": "Concise and relevant task title",
  "description": "Brief task explanation (2-3 sentences maximum). Focus on the main objective and key requirements."
}

IMPORTANT:
- ONLY return pure JSON in your response.
- DO NOT include code block syntax or markdown formatting.
- DO NOT add any extra explanations, comments, or introductory text—just return the JSON object.
- Keep the description SHORT and CONCISE (maximum 2-3 sentences).
- Do NOT include sub-tasks, actionable steps, or detailed breakdowns.

Generate a task title and description based on this request: "${userRequest}"`
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 1024
        }
      }

      const response = await fetch(apiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(requestBody)
      })

      if (!response.ok) {
        throw new Error(`Gemini API call failed: ${response.statusText}`)
      }

      const data = await response.json()

      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

      if (!generatedText) {
        throw new Error("No content generated by Gemini API")
      }

      let parsedResponse
      try {
        parsedResponse = JSON.parse(generatedText.trim())
      } catch {
        const jsonMatch =
          generatedText.match(/```json\n([\s\S]+?)\n```/) ||
          generatedText.match(/```\n([\s\S]+?)\n```/) ||
          generatedText.match(/\{[\s\S]*\}/)

        if (jsonMatch) {
          parsedResponse = JSON.parse(jsonMatch[1] || jsonMatch[0])
        } else {
          throw new Error("Could not extract valid JSON from response")
        }
      }

      return {
        title: parsedResponse.title || "Generated Task",
        description: parsedResponse.description || "Task description not available"
      }
    } catch (error) {
      console.warn("Gemini API failed, using simulated response:", error)
      return simulateAiResponse(userRequest)
    }
  } catch (error) {
    console.error("Error generating task draft:", error)
    return simulateAiResponse(userRequest)
  }
}
